# Generated by Django 5.0 on 2025-02-24 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('borrower_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('passport_number', models.CharField(blank=True, max_length=20)),
                ('driving_license', models.CharField(blank=True, max_length=20)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('loan_sanction_date', models.DateField(blank=True, null=True)),
                ('loan_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('witness_details', models.JSONField(blank=True, default=dict)),
                ('emi_history', models.JSONField(blank=True, default=dict)),
                ('credibility_summary', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
