# Generated by Django 5.0 on 2025-02-25 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0002_loandocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property_owner', models.CharField(max_length=200)),
                ('property_area', models.CharField(max_length=100)),
                ('property_location', models.TextField()),
                ('property_coordinates', models.CharField(blank=True, max_length=100)),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loan_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('risk_summary', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
