# Generated by Django 5.0 on 2025-02-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0003_propertydocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loandocument',
            old_name='borrower_name',
            new_name='borrower_name_original',
        ),
        migrations.RenameField(
            model_name='loandocument',
            old_name='father_name',
            new_name='borrower_name_translated',
        ),
        migrations.RenameField(
            model_name='loandocument',
            old_name='credibility_summary',
            new_name='credibility_summary_translated',
        ),
        migrations.RenameField(
            model_name='loandocument',
            old_name='spouse_name',
            new_name='father_name_translated',
        ),
        migrations.RenameField(
            model_name='loandocument',
            old_name='sex',
            new_name='sex_translated',
        ),
        migrations.RenameField(
            model_name='propertydocument',
            old_name='property_location',
            new_name='property_location_original',
        ),
        migrations.RenameField(
            model_name='propertydocument',
            old_name='property_owner',
            new_name='property_owner_original',
        ),
        migrations.RenameField(
            model_name='propertydocument',
            old_name='risk_summary',
            new_name='risk_summary_original',
        ),
        migrations.AddField(
            model_name='loandocument',
            name='borrower_name_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='credibility_summary_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='credibility_summary_original',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loandocument',
            name='father_name_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='father_name_original',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loandocument',
            name='sex_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='sex_original',
            field=models.CharField(default='M', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loandocument',
            name='spouse_name_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='spouse_name_original',
            field=models.CharField(default='Maam', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loandocument',
            name='spouse_name_translated',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property_location_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property_location_translated',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property_owner_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property_owner_translated',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='risk_summary_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='risk_summary_translated',
            field=models.TextField(blank=True),
        ),
    ]
