# Generated by Django 5.0 on 2025-02-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0004_rename_borrower_name_loandocument_borrower_name_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='loan_amount',
            field=models.CharField(blank=True, default='25,00,00 ₹', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='loan_balance',
            field=models.CharField(blank=True, default='25,00,00 ₹', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='loan_limit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='property_value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
