# Generated by Django 5.0 on 2025-02-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0005_alter_loandocument_loan_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='property_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='risk_summary_original',
            field=models.TextField(blank=True),
        ),
    ]
