# Generated by Django 5.0 on 2025-02-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0006_alter_propertydocument_property_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='property_location_original',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='property_owner_original',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
