# Generated by Django 5.0 on 2025-02-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0007_alter_propertydocument_property_location_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
