# Generated by Django 5.0 on 2025-02-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0008_alter_loandocument_aadhar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandocument',
            name='credit_score',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='loan_purpose_language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='loan_purpose_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='loan_purpose_translated',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='loan_term_months',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='monthly_income',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='borrower_name_language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='borrower_name_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='borrower_name_translated',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='credibility_summary_language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='credibility_summary_original',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='credibility_summary_translated',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='father_name_language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='father_name_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='father_name_translated',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='loan_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='sex_language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='sex_original',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='sex_translated',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='spouse_name_language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='spouse_name_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='spouse_name_translated',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
