# Generated by Django 5.0 on 2025-02-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0009_loandocument_credit_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='aadhar_number',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='borrower_name_language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='borrower_name_original',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='borrower_name_translated',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='credibility_summary_language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='credibility_summary_original',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='credibility_summary_translated',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='credit_score',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='driving_license',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='emi_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='father_name_language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='father_name_original',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='father_name_translated',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='loan_amount',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='loan_balance',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='loan_purpose_language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='loan_purpose_original',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='loan_purpose_translated',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='loan_term_months',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='monthly_income',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='pan_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='passport_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='sex_language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='sex_original',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='sex_translated',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='spouse_name_language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='spouse_name_original',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='spouse_name_translated',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='witness_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
