# Generated by Django 5.0 on 2025-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0010_alter_loandocument_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='pan_number',
            field=models.CharField(max_length=10, verbose_name='PAN Number'),
        ),
    ]
