# Generated by Django 5.0 on 2025-02-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0012_alter_loandocument_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Number'),
        ),
    ]
