# Generated by Django 5.0 on 2025-02-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0013_alter_loandocument_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='driving_license',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
