# Generated by Django 5.0 on 2025-02-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0015_alter_loandocument_credit_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='loan_balance',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
