# Generated by Django 5.0 on 2025-02-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0016_alter_loandocument_loan_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydocument',
            old_name='property_area',
            new_name='property_area_original',
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property_area_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property_area_translated',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
