# Generated by Django 5.0 on 2025-03-10 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0018_customextraction_extractionprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionprompt',
            name='document_type',
            field=models.CharField(choices=[('loan', 'Loan Document'), ('property', 'Property Document'), ('table', 'Table Document')], max_length=20),
        ),
        migrations.CreateModel(
            name='TableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('table_data', models.JSONField(blank=True, default=dict)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
